apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: calendar
        - name: POSTGRES_USER
          value: calendar_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: calendar-secrets
              key: postgres-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
