apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-scheduler
  namespace: calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-scheduler
  template:
    metadata:
      labels:
        app: calendar-scheduler
    spec:
      containers:
      - name: calendar-scheduler
        image: calendar-scheduler:latest
        imagePullPolicy: Never
        env:
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: calendar_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: calendar-secrets
              key: postgres-password
        - name: POSTGRES_DB
          value: calendar
        - name: RABBITMQ_HOST
          value: rabbitmq-service
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: calendar_user
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: calendar-secrets
              key: rabbitmq-password
        volumeMounts:
        - name: config-volume
          mountPath: /app/scheduler_config.yaml
          subPath: scheduler-config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: calendar-config
