FROM golang:1.25-alpine AS builder

WORKDIR /app

# Копируем go mod файлы
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Собираем интеграционные тесты
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o integration-tests ./tests/integration

# Финальный образ
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Копируем бинарный файл
COPY --from=builder /app/integration-tests .

# Запускаем тесты
CMD ["./integration-tests"]
