apiVersion: v1
kind: Service
metadata:
  name: calendar-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: calendar-api
  ports:
  - port: {{ .Values.api.servicePort }}
    targetPort: {{ .Values.api.port }}
  type: ClusterIP
