apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-scheduler
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      app: calendar-scheduler
  template:
    metadata:
      labels:
        app: calendar-scheduler
    spec:
      containers:
      - name: calendar-scheduler
        image: {{ .Values.image.repository }}-scheduler:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: calendar_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          value: calendar
        - name: RABBITMQ_HOST
          value: rabbitmq-service
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: calendar_user
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        volumeMounts:
        - name: config-volume
          mountPath: /app/scheduler_config.yaml
          subPath: scheduler-config.yaml
        resources:
          {{- toYaml .Values.scheduler.resources | nindent 12 }}
      volumes:
      - name: config-volume
        configMap:
          name: calendar-config
