apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  password: {{ .Values.secrets.postgresPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  password: {{ .Values.secrets.rabbitmqPassword | b64enc }}
