logger:
  level: debug

server:
  host: "localhost"
  port: 8080
  grpc_port: :6523

storage:
  type: database # can be memory
  host: localhost
  port: 5434
  user: calendar_user
  password: calendar_pass
  database: calendar
  sslmode: disable


