apiVersion: v1
kind: ConfigMap
metadata:
  name: calendar-config
  namespace: calendar
data:
  calendar-config.yml: |
    logger:
      level: debug
    server:
      host: 0.0.0.0
      port: 8888
      grpc_port: :6523
    storage:
      type: database
      host: postgres-service
      port: 5432
      user: calendar_user
      password: calendar_pass
      database: calendar
      sslmode: disable
