apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-api
  namespace: calendar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calendar-api
  template:
    metadata:
      labels:
        app: calendar-api
    spec:
      containers:
      - name: calendar-api
        image: calendar:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888

        volumeMounts:
        - name: config-volume
          mountPath: /app/configs/config.yml
          subPath: calendar-config.yml
        livenessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: calendar-config
